all: Exception.cpp Clientprogram.cpp TreeNode.cpp BinarySearchTree.cpp AVLTree.cpp BinaryTree.cpp  Item.cpp Key.cpp
	clang++ -std=c++11 Exception.cpp Clientprogram.cpp TreeNode.cpp BinarySearchTree.cpp AVLTree.cpp BinaryTree.cpp  Item.cpp Key.cpp -o holy 
	./holy

build: Exception.cpp Clientprogram.cpp TreeNode.cpp BinarySearchTree.cpp AVLTree.cpp BinaryTree.cpp  Item.cpp Key.cpp
	clang++ -std=c++11 Exception.cpp Clientprogram.cpp TreeNode.cpp BinarySearchTree.cpp AVLTree.cpp BinaryTree.cpp  Item.cpp Key.cpp -o holy
clean: 
	$(RM) ./holy

run: holy
	./holy

