all: Clientprogram.cpp TreeNode.cpp BinaryTree.cpp  Item.cpp Key.cpp
	g++ Clientprogram.cpp TreeNode.cpp BinaryTree.cpp  Item.cpp Key.cpp -o Gobin
	./Gobin

build: Clientprogram.cpp TreeNode.cpp BinaryTree.cpp  Item.cpp Key.cpp
	g++ Clientprogram.cpp TreeNode.cpp BinaryTree.cpp  Item.cpp Key.cpp -o Gobin
clean: 
	$(RM) ./Gobin

run: Gobin
	./Gobin
