all: Exception.cpp Client.cpp TreeNode.cpp BinaryTree.cpp  Item.cpp Key.cpp
	g++ Exception.cpp Client.cpp TreeNode.cpp BinaryTree.cpp  Item.cpp Key.cpp -o Golink -std=c++11
	./Golink

build: Exception.cpp Client.cpp TreeNode.cpp BinaryTree.cpp  Item.cpp Key.cpp
	g++ Exception.cpp Client.cpp TreeNode.cpp BinaryTree.cpp  Item.cpp Key.cpp -o Golink -std=c++11
clean: 
	$(RM) ./Golink

run: Golink
	./Golink
