all: Exception.cpp Clientprogram.cpp TreeNode.cpp BinarySearchTree.cpp BinaryTree.cpp  Item.cpp Key.cpp
	clang++ -std=c++11 Exception.cpp Clientprogram.cpp TreeNode.cpp BinarySearchTree.cpp BinaryTree.cpp  Item.cpp Key.cpp -o Dodictionary 
	./Dodictionary

build: Exception.cpp Clientprogram.cpp TreeNode.cpp BinarySearchTree.cpp BinaryTree.cpp  Item.cpp Key.cpp
	clang++ -std=c++11 Exception.cpp Clientprogram.cpp TreeNode.cpp BinarySearchTree.cpp BinaryTree.cpp  Item.cpp Key.cpp -o Dodictionary
clean: 
	$(RM) ./Dodictionary

run: Dodictionary
	./Dodictionary
